name: ArgoTunnel
options:
  bundleIdPrefix: com.argotunnel
settings:
  base:
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  ArgoTunnel:
    type: application
    platform: iOS
    sources:
      - path: ArgoTunnel
    info:
      path: ArgoTunnel/Info.plist
    settings:
      base:
        INFOPLIST_FILE: ArgoTunnel/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.argotunnel.app
    dependencies:
      - target: PacketTunnel
  PacketTunnel:
    type: app-extension
    platform: iOS
    sources:
      - path: PacketTunnelProvider
    info:
      path: PacketTunnelProvider/Info.plist
    settings:
      base:
        INFOPLIST_FILE: PacketTunnelProvider/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.argotunnel.app.extension
        CODE_SIGN_ENTITLEMENTS: PacketTunnelProvider/Entitlements.plist
